### ISSUE TITLE
Replace yew_services to yew::services

### ISSUE THREAD

**Issue by m-s-h-1** [LighghtEeloo/flow.er#1]
In main.rs line 143, it is written yew_services. Please change it to yew::services. Also, comment out yew_services in cargo.toml and the path to yew should not be there. There just "" these are fine. With a path, it does not compile on linux and with your specific path, it would not compile on any other pc :) :+1: .

**Comment by LighghtEeloo** [comment]
Yeah, you are right. This version is still under heavy development and is currently using yew from its master branch (which is supposed to be 0.18 in the future). So I maintain a version of yew locally, which is why you're seeing the path.

For now if you are trying to run it yourself, you can:
1. Choose branch `tracer-yew-lock`.
2. Git clone [yew](https://github.com/yewstack/yew) and choose the master branch.
3. Change the path in `Cargo.toml`.

But anyway, in the short future I may:

A. take your advice and use yew 0.17 instead, meaning using `yew::services`.   
B. wait until yew 0.18 come out and update Cargo.toml  

either way you'll no longer worry about "local path".

**Comment by LighghtEeloo** [comment]
In fact, this situation is caused because I'm lazy ( yeah ) and don't want to change my code in the future:   
https://github.com/yewstack/yew/pull/1693

**Comment by LighghtEeloo** [comment]
commit 96846dda (already committed on branch `dev`) has fixed this.
